#ifndef MTPOBJECTFORMATS__H
#define MTPOBJECTFORMATS__H

#define MTP_OBJECT_FORMAT_FOLDER 0x3001
#define MTP_OBJECT_FORMAT_BINARY 0x3000
#define MTP_OBJECT_FORMAT_JPG 0x3801
#define MTP_OBJECT_FORMAT_PNG 0x380B

#endif