#ifndef RETURNCONSTANTS__H
#define RETURNCONSTANTS__H

enum ReturnConstants{
	MUMTP_SUCCESS,
	MUMTP_DEVICE_VIDPID_NOT_FOUND,
	MUMTP_DEVICE_INTERFACE_CLAIM_FAILED,
	MUMTP_OPERATION_FAILED,
	MUMTP_OPEN_SESSION_FAILED,
	MUMTP_STORAGE_SYNC_FAILED,
	MUMTP_SEND_PACKET_FAILED,
	MUMTP_RECEIVE_DATA_FAILED,
	MUMTP_SESSION_IS_NOT_OPEN,
	MUMTP_INVALID_STORAGE,
	MUMTP_UNSUPPORTED_PROPERTY_ID,
	MUMTP_INVALID_DATA_READ,
	MUMTP_HANDLE_NOT_FOUND,
	MUMTP_INVALID_INPUTOUTPUT_OBJECT,
	MUMTP_HANDLE_CHILDREN_NOT_FOUND,
	MUMTP_REQUIRED_DOWNLOAD_IS_FOLDER,
	MUMTP_NO_WRITER_NOR_FILENAME_RECV,
};

#endif